# Generated by Django 5.0.6 on 2024-09-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreview',
            name='image2',
        ),
    ]
